---
name: makepkg

on:
  push:
    branches:
      - 'pkg/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:base-devel

    steps:
      - name: Setup container
        run: |
          pacman-key --init
          pacman -Syy --needed --noconfirm archlinux-keyring
          pacman -Syu --needed --noconfirm namcap
          useradd -m github

      - uses: actions/checkout@v3

      - name: Run makepkg
        run: runuser -u github -g root -- makepkg -s

      - name: Test PKGBUILD
        run: namcap PKGBUILD

      - name: Test final package
        run: namcap *.pkg.tar.zst

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
