---
name: makepkg

on:
  push:
    branches:
      - 'pkg/*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: archlinux:base-devel

    steps:
      - name: Setup container
        run: |
          pacman-key --init
          pacman -Sy archlinux-keyring
          pacman -Syu

      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
