name: Build packages

on: push

jobs:
  makepkg:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest
      options: --privileged --tmpfs /run

    steps:
    - name: Setup Arch Linux container
      run: |
        echo 'Server = https://arch.mirror.constant.com/$repo/os/$arch' > /etc/pacman.d/mirrorlist
        pacman -Sy --noconfirm base devtools
        pacman -Syuu --noconfirm
        systemd-machine-id-setup

    - uses: actions/checkout@v2

    - name: Build packages
      run: ${GITHUB_WORKSPACE}/tools/build.sh
