name: Build packages

on: push

jobs:
  makepkg:
    runs-on: ubuntu-latest

    container:
      image: archlinux:latest

    steps:
    - name: Set pacman mirror
      run: echo 'Server = https://arch.mirror.constant.com/$repo/os/$arch' > /etc/pacman.d/mirrorlist

    - name: Install devtools
      run: pacman -Sy --noconfirm devtools

    - name: Update system
      run: pacman -Syuu --noconfirm

    - uses: actions/checkout@v2
