name: Build packages

on: push

jobs:
  makepkg:
    runs-on: ubuntu-latest

    container:
      image: archlinux/archlinux:base-devel

    steps:
    - name: Update Arch Linux container
      run: |
        adduser -m builder

    - uses: actions/checkout@v2

    - name: Build packages
      run: ${GITHUB_WORKSPACE}/tools/build.sh
